name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Install and configure vcpkg (Windows)
      if: runner.os == 'Windows'
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install openssl-windows:x64-windows
        .\vcpkg\vcpkg install openssl:x64-windows-static
        .\vcpkg\vcpkg integrate install
        echo "VCPKG_ROOT=$(pwd)\vcpkg" >> $GITHUB_ENV
        echo "VCPKGRS_DYNAMIC=1" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

